# Site settings
title: Hrain's blog
SEOTitle: 高欣的博客 | Hrain's blog
header-img: img/about-desktop.jpg
email: 471429282@qq.com.com
description: "Every failure is leading towards success."
keyword: "BY, BY Blog, 高欣的博客, gaoxin, 高欣, java, php, pyhton"
url: "https://paydebt.github.io/"          
baseurl: ""     
github_repo: "https://paydebt.github.io/" 


sidebar: true                           
sidebar-about-description: "我不敢下苦功琢磨自己，怕终于知道自己并非珠玉；<br>然而心中又存着一丝希冀，便又不肯甘心与瓦砾为伍"
sidebar-avatar: /img/about-me.jpg      




RSS: false

permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          

gems: [jekyll-paginate]

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important


{% if site.gitalk.enable %}
<!-- Link Gitalk 的支持文件  -->
<link rel="stylesheet" href="https://unpkg.com/gitalk/dist/gitalk.css">
<script src="https://unpkg.com/gitalk@latest/dist/gitalk.min.js"></script>

<div id="gitalk-container"></div>
    <script type="text/javascript">
    var gitalk = new Gitalk({

    // gitalk的主要参数
        clientID: c30dab81d2ed10ea5f02
        clientSecret: 7e20f920fad965c8e7cf71c9ea4cdb022339f000
        repo: PingLun
        owner: PayDebt
        admin: PayDebt
        id: decodeURI(window.location.pathname)
    
    });
    gitalk.render('gitalk-container');
</script>
{% endif %}

ba_track_id: 639d69ba46060f864b005f1d97856c8c

# Google Analytics
ga_track_id: UA-90855596-1            # Format: UA-xxxxxx-xx
ga_domain: http://www.gaoxinya.xyz               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto




# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# Friends
friends: [
    {
        title: "Hrain's 博客园",
        href: "http://www.cnblogs.com/Hrain"
    },{
        title: "Hrain's CSDN",
        href: "http://blog.csdn.net/gaoxin_gx"
    },{
        title: "微博",
        href: "http://weibo.com/u/6735644192?is_all=1"
    },{
        title: "baidu",
        href: "http://www.baidu.com"
    }
]
