# Site settings
title: Hrain's blog
SEOTitle: 高欣的博客 | Hrain's blog
header-img: img/post-bg-desk.jpg
email: 471429282@qq.com.com
description: "Every failure is leading towards success."
keyword: "BY, BY Blog, 高欣的博客, gaoxin, 高欣, java, php, pyhton"
url: "https://paydebt.github.io/"          
baseurl: ""     
github_repo: "https://paydebt.github.io/" 


sidebar: true                           
sidebar-about-description: "Goals determine what you going to be!"
sidebar-avatar: /img/about-me.jpg      




RSS: false

permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          

gems: [jekyll-paginate]

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: gaoxin

# Gitalk
gitalk:
  enable: false    #是否开启Gitalk评论,开启后将这里改为true
  clientID: f2c84e7629bb1446c1a4                            #生成的clientID
  clientSecret: ca6d6139d1e1b8c43f8b2e19492ddcac8b322d0d    #生成的clientSecret
  repo: paydebt.github.io    #仓库名称
  owner: gaoxin    #github用户名
  admin: gaoxin
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: 639d69ba46060f864b005f1d97856c8c

# Google Analytics
ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
ga_domain: gaoxinya.xyz               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "Hrain's 博客园",
        href: "http://www.cnblogs.com/Hrain"
    },{
        title: "Hrain's CSDN",
        href: "https://blog.csdn.net/gaoxin_gx"
    },{
        title: "微博",
        href: "https://weibo.com/u/6735644192?is_all=1"
    },{
        title: "baidu",
        href: "www.baidu.com"
    }
]
