# Site settings
title: BY ZhangWenxiang
SEOTitle: 张文翔的博客 | BY ZhangWenxiang
header-img: img/post-bg-desk.jpg
email: zhangwenxiang0302@gmail.com  1007201991@qq.com
description: "关于机器学习、智能算法、统计分析相关的总结和思考，尤其是计算广告和推荐系统相关领域."
keyword: "计算广告、推荐系统、机器学习、人工智能"
url: "http://Demmon-tju.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/Demmon-tju/Demmon-tju.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Nothing is difficult,everything is a challenge. Through adversity to the stars. To the last man, to the last second, to the last minute . We fight! We fight! We fight!"
sidebar-avatar: /img/wade.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     qiubaiying
zhihu_username:     龙翔天翼
github_username:    Demmon-tju
facebook_username:  None
jianshu_username:   None
csdn_username:   我叫龙翔天翼




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: c1662352f7c2cc5f6def                           #生成的clientID
  clientSecret: 60a508afae5bd28705822722fb2414ce7492b6e1    #生成的clientSecret
  repo: Demmon-tju.github.io    #仓库名称
  owner: Demmon-tju    #github用户名
  admin: Demmon-tju
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "WY",
        href: "http://zhengwuyang.com"
    },{
        title: "简书·BY",
        href: "http://www.jianshu.com/u/e71990ada2fd"
    },{
        title: "Apple",
        href: "https://apple.com"
    },{
        title: "Apple Developer",
        href: "https://developer.apple.com/"
    }
]
