# Site settings
title: Fan Feng
SEOTitle: Eric's blog | Fan Feng
header-img: img/post-bg-desk.jpg
email: ffeng1017@gmail.com
description: "Those violent delights have violent ends."
keyword: "Eric, fanfeng, Machine Learning, Deep Learning, Computer Vision, C++"
url: "http://ffengeng.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/ffengeng/ffengeng.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Goals determine what you going to be!"
sidebar-avatar: /img/about.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     qiubaiying
zhihu_username:     feng-fan-61-24
github_username:    ffengeng
facebook_username:  fan.feng.125
twitter_username:   ffeng01




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
disqus_username: ericfanfeng

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 7b8d76e8b3f38251d44d   #生成的clientID
  clientSecret: eb61e10222a9ac4142f4ce6f704c9c1f9409b40d  #同上
  repo: ffengeng.github.io    #仓库名称
  owner: ffengeng    #github用户名
  admin: ffengeng
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
# ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_track_id: 'UA-114678753-1'            # Format: UA-xxxxxx-xx
ga_domain: http://ffengeng.github.io               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "Hanjing Wong",
        href: "https://www.facebook.com/profile.php?id=100013020851329"
    },{
        title: "Xingguo Chen",
        href: "https://cs.nju.edu.cn/rl/people/chenxg/"
    },{
        title: "",
        href: ""
    },{
        title: "Andrew Zhu",
        href: "https://scholar.google.com/citations?user=CtT7JZgAAAAJ&hl=zh-CN"
    }
]
