# Site settings
title: BY Blog
SEOTitle: 董文文的博客 | BY Blog
header-img: img/post-bg-desk.jpg
email: 1204143402@qq.com
description: "不学计算机，难道搬砖吗？"
url: "http://study-cell.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/qiubaiying/qiubaiying.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "切忌短期高估自己，长期低估自己!"
sidebar-avatar: /img/about-BY-gentle.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
#github_username:    study-cell
csdn_username:     mo_49796894



















