# Site settings
title: Coding Lane
SEOTitle: 记录成长 | Coding Lane
timezone: Asia/Shanghai
header-img: img/bit (3).jpg
email: xie96808@gmail.com
description: "Rest at the end, not in the middle"
keyword: "NONE"
url: "http://xie96808.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'


# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "记忆之中没有辛苦，只有遗憾"
sidebar-avatar: /img/touxiang2.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     NONE
zhihu_username:     xie-yu-wei-35
github_username:    xie96808
#facebook_username:  NONE
#jianshu_username:   NONE
twitter_username:  BillyXie5




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 12
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important


<!-- Gitalk 评论 start  -->
{% if site.gitalk.enable %}
<!-- Link Gitalk 的支持文件  -->
<link rel="stylesheet" href="https://unpkg.com/gitalk/dist/gitalk.css">
<script src="https://unpkg.com/gitalk@latest/dist/gitalk.min.js"></script>

<div id="gitalk-container"></div>
    <script type="text/javascript">
    var gitalk = new Gitalk({

    // gitalk的主要参数
		clientID: `4dede977f9d18025b3b5`,
		clientSecret: `b1607f2c0a2ed2a143c60b1df7cc683d22787bce`,
		repo: `xie96808.github.io`,
		owner: 'xie96808',
		admin: ['xie96808'],
		id: 'location.href',
    
    });
    gitalk.render('gitalk-container');
</script>
{% endif %}
<!-- Gitalk end -->







# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 2              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

